### PR TITLE
fixing linter issues

### PR DESCRIPTION
**Pull request by joergi**

### CODE REVIEW

**Comment by joergi** [comment]
maybe you have some idea to fix the linter issues @Rubemlrm ?

**Comment by joergi** [comment]
linux/mac os linter is green now

**Comment by rubemlrm** [comment]
@joergi just fix that little detail relative to missing double quote on the $OUTDIR variable and i will merge this after that =)

**Comment by joergi** [comment]
@Rubemlrm - now the Linux linter is fixed - now only someone has to have a look for the Windows one :grin:

**Comment by joergi** [comment]
blocks PR #6

**Comment by rubemlrm** [comment]
Good one =)

**Comment by joergi** [comment]
You merged, but the power shell linter was still red @Rubemlrm

**Comment by joergi** [comment]
Screenshot_20200718-130802
A merge with red should not have been able to merge?

**Comment by joergi** [comment]
I opened a new ticket for the powershell linter
#7

**Pull request merged**
